name: Build Backend and Frontend

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - SampleApp/BackEnd/BackEnd.csproj
          - SampleApp/FrontEnd/FrontEnd.csproj

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore ${{ matrix.project }}

      - name: Build project
        run: dotnet build ${{ matrix.project }} --no-restore --configuration Release